### ISSUE TITLE
Build instructions fail

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [msys2-unofficial/MSYS2-packages#12]
Somehow, the recommended line
```
pacman -S --needed base-devel msys2-devel
```
does not install `autotools` or is missing some subpackage, which is needed to build `isync`. This is fixed by
```
pacman -S autotools
```
before changing to `isync` and building the package.

**Comment by damon-kwok** [comment]
@juanjosegarciaripoll Fixed, Thanks.
